# Generated by Django 6.0.3 on 2026-03-18 04:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(5, 'title must be at least 5 characters long.')]),
        ),
    ]
