# Generated by Django 6.0.3 on 2026-04-01 22:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0011_alter_task_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=60, unique=True, validators=[django.core.validators.MinLengthValidator(5, 'Project name mist be at least 5 characters long.')]),
        ),
    ]
